---
# ACL management playbook
- name: Manage POSIX ACLs
  hosts: all
  become: true
  vars:
    files:
      test:
        member: vagrant
        location: /home/vagrant/02/3
        permission: "---"
        type: group
      python2.7:
        member: bamboo-agent
        location: /home/vagrant/02/4
        permission: rwx
        type: user
  roles:
    - facl
