---
# Group management playbook
- name: Manage local groups
  hosts: all
  become: true
  vars:
    local_groups:
      vboxusers:
        ensure: present
        gid: "10050"
      libvirt:
        ensure: present
        gid: "10051"
  roles:
    - group_merge
